### ISSUE TITLE
Certain bugs should trigger an email to developers

### ISSUE THREAD

**Issue by nairabhishek73** [DalgoT4D/grafana#6]
e.g. "Failed to create connector block for custom commcare"

**Comment by fatchat** [comment]
should we do this in loki

**Comment by fatchat** [comment]
logQL string matching operators: |=, |~ for contains and regex. Replace | with ! for negation

5 range aggregation functions: rate(), count_over_time(), bytes_rate(), bytes_over_time(), absent_over_time(). these take a data source (stream?) and a time window within which to aggregate

when we define a "query and alert condition", we will compute the range aggregation function every minute and get a time-series of values. NOTE: if the aggregation is `count_over_time([1h])`, this gives us ONE value - not 60. And the next minute we get another value, and another. We therefore get a vector of values over which we may want to look at

- the maximum 
- the minimum
- the sum, the average, ...
- the last one

the length of the input into the reduction step is defined at the top of the query step - for example we may say "10 minutes ago to now" which will give us 10 data points to be reduced

finally the reduction is compared to a threshold to give us a boolean "alert breached!" 

we next define how to respond to this boolean. in some cases we will want to respond immediately, but in others we may want to wait until we see it fire repeatedly for X minutes - this can be set in the "for" setting in "Alert Evaluation Behavior"

**Comment by nairabhishek73** [comment]
How's this looking?

**Comment by fatchat** [comment]
we are detecting errors and emails are being triggered by loki. but we're catching false positives, for example

```
01:19:57.437 | WARNING | uvicorn.error - Invalid HTTP request received.
01:54:29.611 | WARNING | uvicorn.error - Invalid HTTP request received.
```

**Comment by Abhishek-N** [comment]
> we are detecting errors and emails are being triggered by loki. but we're catching false positives, for example
> 
> ```
> 01:19:57.437 | WARNING | uvicorn.error - Invalid HTTP request received.
> 01:54:29.611 | WARNING | uvicorn.error - Invalid HTTP request received.
> ```

this alert is triggered by log entries with level `WARNING` and can be fixed by modifying the query to only match entries `error` and `failed` and not from level `WARNING`

**Comment by Abhishek-N** [comment]
added more conditions to the query to avoid triggering emails for false-positives.

` "uvicorn.error.*WARNING.*Invalid HTTP request received" !~ `
`"uvicorn.error.*WARNING.*No supported WebSocket library detected" !~ `
`"uvicorn.error - Unsupported upgrade request" [1h]) > 0`

**Comment by fatchat** [comment]
today's errors were all true positives

**Comment by Ishankoradia** [comment]
@Abhishek-N to try a new approach - to get error messages in email

**Comment by Abhishek-N** [comment]
we cannot silence notifications from firing or resolved instances

https://grafana.com/docs/grafana/latest/alerting/fundamentals/notification-policies/#silences

**Comment by Abhishek-N** [comment]
closing this as the mails that are triggered are mostly for actual errors
